apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevishwa-api
  namespace: default
  labels:
    app: kubevishwa-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubevishwa-api
  template:
    metadata:
      labels:
        app: kubevishwa-api
    spec:
      containers:
      - name: kubevishwa-api
        image: kubevishwa-api:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: kubevishwa-api-tracing-tracing-config
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kubevishwa-api
  namespace: default
  labels:
    app: kubevishwa-api
spec:
  type: NodePort
  selector:
    app: kubevishwa-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
