apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-controller
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-controller
  template:
    metadata:
      labels:
        app: tracing-controller
    spec:
      serviceAccountName: tracing-controller
      containers:
      - name: controller
        image: tracing-controller:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
